name: Hello World

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Greeting
      run: echo "Hello great big World!"

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            pip install pytest

    - name: Run tests
      run: pytest tests/