name: Flake Eight

on: [push]

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            pip install pytest

    - name: Install flake8
      run: pip install flake8

  linting:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
    - name: Run flake8
      run: flake8 src/ tests/

  tests:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
    - name: Run tests
      run: pytest tests/